# Minimal real-nxdk test XBE for the nxkrnl XBE loader -- see main.c.
# Builds with the pinned nxdk submodule; output is bin/default.xbe.
XBE_TITLE = nxkrnl-hello
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS = $(CURDIR)/main.c
include $(NXDK_DIR)/Makefile
