
list(APPEND HAL_XBOX_ASM_SOURCE
    generic/systimer.S
    generic/trap.S
    pic/pic.S)

list(APPEND HAL_XBOX_SOURCE
    generic/beep.c
    generic/cmos.c
    generic/display.c
    generic/dma.c
    generic/drive.c
    generic/halinit.c
    generic/kdpci.c
    generic/memory.c
    generic/misc.c
    generic/nmi.c
    generic/pic.c
    generic/sysinfo.c
    generic/usage.c
    generic/portio.c
    # x86bios.c is the videoprt int 0x10 thunk -- runs the BIOS's
    # video-mode code in V86 via fast486.  Xbox has no PC BIOS (NV2A is
    # programmed directly), videoprt isn't linked, and fast486 is 464 KB.
    # The companion HAL stub at legacy/nxkrnl-x86bios-stub.c keeps the
    # exported entry points so the kernel image still links.
    legacy/nxkrnl-x86bios-stub.c
    legacy/bus/bushndlr.c
    legacy/bus/cmosbus.c
    legacy/bus/isabus.c
    legacy/bus/pcibus.c
    # pci_classes.c / pci_vendors.c (~1.5 MB of pretty PCI vendor/
    # device strings, embedded as INITDATA so HalpDebugPciDumpBus's boot
    # debug print can show "NVIDIA Corporation" next to BDFs) are replaced
    # by a 2-byte stub so the kernel fits in the single-ROM flash budget.
    # See nxkrnl-pci-strings-stub.c.  We still need the generated pci_*.h
    # headers (extern ClassTable / VendorTable) for the bussupp.c includes
    # -- OBJECT_DEPENDS below wires that up.
    legacy/nxkrnl-pci-strings-stub.c
    legacy/bus/sysbus.c
    legacy/bussupp.c
    legacy/halpnpdd.c
    legacy/halpcat.c
    generic/profil.c
    generic/timer.c
    xbox/clock.c
    xbox/halinit.c
    xbox/pci.c
    xbox/reboot.c
    xbox/smbus.c
    xbox/av.c
    xbox/hal.c
    xbox/phy.c
    # Ported cromwell video driver -- programs the NV2A CRTC and one of
    # three TV encoders (Conexant / Focus / Xcalibur) at boot.
    xbox/video/xbox-video-support.c
    xbox/video/BootVgaInitialization.c
    xbox/video/VideoInitialization.c
    xbox/video/conexant.c
    xbox/video/focus.c
    xbox/video/xcalibur.c
    # Ported cromwell PCI bring-up: BootDetectMemorySize +
    # BootAGPBUSInitialization + BootPciPeripheralInitialization, called
    # from NxConfigurePciDevices.
    xbox/pci-bringup/cromwell-pci.c
    pic/irql.c
    pic/pic.c
    pic/processor.c)

add_asm_files(lib_hal_xbox_asm ${HAL_XBOX_ASM_SOURCE})
add_library(lib_hal_xbox OBJECT ${HAL_XBOX_SOURCE} ${lib_hal_xbox_asm})
add_dependencies(lib_hal_xbox bugcodes xdk asm)
#add_pch(lib_hal_xbox xbox/halxbox.h)
target_compile_definitions(lib_hal_xbox PRIVATE SARCH_XBOX)
target_include_directories(lib_hal_xbox PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/xbox
    ${CMAKE_CURRENT_SOURCE_DIR}/xbox/video
    ${CMAKE_CURRENT_SOURCE_DIR}/xbox/pci-bringup)

# bussupp.c #includes pci_classes.h + pci_vendors.h (generated by
# pcidata.cmake's add_custom_command).  lib_hal_legacy picks the dep up
# implicitly by listing pci_*.c in its source list; we don't compile those
# (see the stub above), so wire the header dep on bussupp.c explicitly.
set_source_files_properties(legacy/bussupp.c PROPERTIES OBJECT_DEPENDS
    "${CMAKE_CURRENT_BINARY_DIR}/pci_classes.h;${CMAKE_CURRENT_BINARY_DIR}/pci_vendors.h")
