# KeDelay accumulation test XBE -- exercises KeDelayExecutionThread.
# See main.c.
XBE_TITLE = nxkrnl-kedelay-test
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS = $(CURDIR)/main.c
include $(NXDK_DIR)/Makefile
