if(SARCH STREQUAL "xbox")
    add_subdirectory(xdvdfs)
    add_subdirectory(vfatfs)
    return()
endif()

add_subdirectory(btrfs)
add_subdirectory(cdfs)
add_subdirectory(xdvdfs)
add_subdirectory(ext2)
add_subdirectory(fastfat)
add_subdirectory(fs_rec)
add_subdirectory(msfs)
add_subdirectory(mup)
add_subdirectory(nfs)
add_subdirectory(npfs)
add_subdirectory(ntfs)
add_subdirectory(udfs)
add_subdirectory(vfatfs)
