XBE_TITLE = nxkrnl-sdl-pad-probe
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS = $(CURDIR)/main.c
NXDK_SDL = y
NXDK_CFLAGS += -DENABLE_DEBUG_MSG -DENABLE_ERROR_MSG
include $(NXDK_DIR)/Makefile
