#!/usr/bin/env python3
#
# xb/gen-exports.py -- generate the Xbox-kernel export scaffold.
#
# The Xbox kernel exports ~366 routines BY ORDINAL (NONAME) -- the ABI an
# XBE imports through its kernel thunk table.  This file gives xboxkrnl.exe
# a real PE export directory of those ordinals.
#
# Reads nxdk's xboxkrnl.exe.def (community-reverse-engineered canonical
# ordinal list; CC0) together with xb/ordinals.map (which symbol implements
# which ordinal) and emits:
#
#   <out.spec>  a spec2def spec: one `<ord> <conv> -noname` line per ordinal,
#               pointing at either the mapped real symbol or a scaffold stub.
#   <out.c>     the scaffold: a correct-arity, self-naming bugcheck stub for
#               each unmapped function ordinal, a zeroed datum for each
#               unmapped DATA ordinal, and a one-line marker for each mapped
#               ordinal so the file is scannable.
#
# Scaffold stubs use the ordinal's exact arity and calling convention so the
# title's callee-cleanup pop stays balanced and the bugcheck names exactly
# which ordinal to implement next.
#
# Map syntax (xb/ordinals.map):
#   <ord>  <symbol>                          mapped to <symbol>
#   <ord>  <symbol>  <internal_name>         mapped, asm-level symbol differs
#                                            (spec2def 'name() _internal' form)
#   <ord>  =<value>                          unmapped DATA, scaffold initializer
#                                            override (default 0)
#   <ord>                                    unmapped; reserves a slot just for
#                                            a trailing `# comment` to surface
#                                            in the spec
# Any line may end with `# free-form comment`, which becomes the spec's
# trailing `; ` annotation (parenthesised after the canonical xboxkrnl name).
#
# usage: xb/gen-exports.py <xboxkrnl.exe.def> <ordinals.map> <out.spec> <out.c>
#
import re
import sys

XB_BUGCHECK_UNIMPL = '0xE0000002'   # P1 = the unimplemented ordinal


def parse_def(path):
    """Yield (ordinal, name, conv, argbytes, is_data) for each export."""
    in_exports = False
    for raw in open(path):
        line = raw.split(';', 1)[0].strip()
        if not line:
            continue
        if line == 'EXPORTS':
            in_exports = True
            continue
        if not in_exports or line.startswith('LIBRARY'):
            continue

        tok = line.split()
        decorated, ordinal = tok[0], int(tok[2])
        is_data = 'DATA' in tok[3:]

        if decorated.startswith('@'):           # @Name@N -- __fastcall
            conv = 'fastcall'
            name, argbytes = re.match(r'@([^@]+)@(\d+)$', decorated).groups()
            argbytes = int(argbytes)
        elif '@' in decorated:                  # Name@N -- __stdcall
            conv = 'stdcall'
            name, argbytes = decorated.rsplit('@', 1)
            argbytes = int(argbytes)
        else:                                   # no @N -- __cdecl / data
            conv, name, argbytes = 'cdecl', decorated, 0

        yield ordinal, name, conv, argbytes, is_data


def parse_map(path):
    """Parse the ordinal map.

    Returns {ord: dict(symbol=, internal=, dataval=, comment=)} -- any field
    may be None.  See module docstring for the syntax.
    """
    mapping = {}
    for raw in open(path):
        body, _, comment = raw.partition('#')
        comment = comment.strip() or None
        toks = body.split()
        if not toks:
            continue
        try:
            ordinal = int(toks[0])
        except ValueError:
            continue
        rest = toks[1:]
        entry = {'symbol': None, 'internal': None,
                 'dataval': None, 'comment': comment}
        if rest:
            if rest[0].startswith('='):
                entry['dataval'] = rest[0][1:]
            else:
                entry['symbol'] = rest[0]
                if len(rest) >= 2:
                    entry['internal'] = rest[1]
        mapping[ordinal] = entry
    return mapping


def _trailing(name, comment):
    """Format `<xboxkrnl_name>[ (<comment>)]` for spec trailing ; annotations."""
    return '%s (%s)' % (name, comment) if comment else name


def main():
    def_path, map_path = sys.argv[1], sys.argv[2]
    spec_path, c_path = sys.argv[3], sys.argv[4]
    exports = sorted(parse_def(def_path), key=lambda e: e[0])
    mapping = parse_map(map_path)

    spec = [
        '; Generated by ntoskrnl/xb/gen-exports.py -- do not edit.',
        '; Edit ntoskrnl/xb/ordinals.map and regenerate instead.',
        '; Xbox-kernel ordinal export directory.',
        '',
    ]
    c = [
        '/* Generated by ntoskrnl/xb/gen-exports.py -- do not edit. */',
        '/* Edit ntoskrnl/xb/ordinals.map and regenerate instead. */',
        '/* Xbox-kernel export scaffold. */',
        '#include <ntdef.h>',
        '#include <ntifs.h>',
        '',
        '#define XB_UNIMPL  ((ULONG)' + XB_BUGCHECK_UNIMPL + ')',
        '',
        '__attribute__((noreturn))',
        'static void XbExpBugCheck(ULONG ord) {',
        '    KeBugCheckEx(XB_UNIMPL, ord, 0, 0, 0);',
        '}',
        '',
    ]

    nfunc = ndata = nmapped = 0
    for ordinal, name, conv, argbytes, is_data in exports:
        entry = mapping.get(ordinal, {})
        mapped = entry.get('symbol')
        internal = entry.get('internal')
        dataval = entry.get('dataval')
        comment = entry.get('comment')
        if mapped:
            nmapped += 1

        trailing = '  ; ' + _trailing(name, comment)

        if is_data:
            ndata += 1
            if mapped:
                # Mapped DATA: the export-directory slot is the address of the
                # named symbol (defined elsewhere in the kernel image).  When
                # an internal name is given (third column), the exported name
                # is `mapped` but the linker symbol is `internal` -- lets us
                # rebind e.g. ExEventObjectType to a Xbox-shape shim without
                # colliding with ReactOS's POBJECT_TYPE pointer.
                linker_sym = internal or mapped
                spec.append('%d extern -noname %s %s%s'
                            % (ordinal, mapped, linker_sym, trailing))
                c.append('/* ord %d %s -- DATA mapped to %s */'
                         % (ordinal, name, linker_sym))
            else:
                # Unmapped DATA: emit a zeroed (or overridden) scaffold datum.
                sym = 'XbExpData_%d' % ordinal
                c.append('/* ord %d %s -- DATA (scaffold) */' % (ordinal, name))
                c.append('ULONG_PTR %s = %s;' % (sym, dataval or '0'))
                spec.append('%d extern -noname %s %s%s'
                            % (ordinal, sym, sym, trailing))
            continue

        nfunc += 1
        nargs = argbytes // 4
        args = ' '.join(['long'] * nargs)

        if mapped:
            # Mapped function: spec points at the real symbol; no scaffold.
            override = ' ' + internal if internal else ''
            spec.append('%d %s -noname %s(%s)%s%s'
                        % (ordinal, conv, mapped, args, override, trailing))
            c.append('/* ord %d %s -- mapped to %s */' % (ordinal, name, mapped))
            continue

        # Unmapped function: emit a minimal bugcheck stub.  No DbgPrint name
        # string (saves ~50 bytes of .rdata per ordinal); the bugcheck arg is
        # the ordinal -- xrefs against xb/ordinals.map.
        sym = 'XbExpStub_%d' % ordinal
        cargs = ', '.join('ULONG a%d' % i for i in range(nargs)) or 'void'
        argtypes = ', '.join(['ULONG'] * nargs) or 'void'
        ccmac = '__fastcall' if conv == 'fastcall' else '__stdcall'
        if conv == 'cdecl':
            ccmac = '__cdecl'
        c.append('/* ord %d %s */' % (ordinal, name))
        c.append('ULONG %s %s(%s);' % (ccmac, sym, argtypes))
        c.append('ULONG %s %s(%s)' % (ccmac, sym, cargs))
        c.append('{ XbExpBugCheck(%d); return 0; }' % ordinal)
        spec.append('%d %s -noname %s(%s)%s'
                    % (ordinal, conv, sym, args, trailing))

    # Reserved PE export directory: IMAGE_EXPORT_DIRECTORY header followed
    # by the AddressOfFunctions table.  ld no longer synthesizes .edata (the
    # .def is not passed to the link; bfd's NONAME handling over-reserved
    # ~6 KB of name-table space and cost a page of section alignment).
    # xb/fix-edata.py fills the function RVAs and AddressOfFunctions
    # post-link and points the export DataDirectory here.  A zero RVA marks
    # an ordinal gap; the XBE loader bugchecks on it.
    max_ordinal = exports[-1][0]
    c.append('const ULONG NxkExportDirectory[10 + %d] = {' % max_ordinal)
    c.append('    0, 0, 0, 0, /* Characteristics, TimeDateStamp, Version, Name */')
    c.append('    1,          /* Base */')
    c.append('    %d,         /* NumberOfFunctions; fix-edata.py checks it */' % max_ordinal)
    c.append('};')

    spec.append('')
    c.append('')
    with open(spec_path, 'w') as f:
        f.write('\n'.join(spec))
    with open(c_path, 'w') as f:
        f.write('\n'.join(c))
    sys.stderr.write('gen-exports: %d ordinals (%d function, %d data); '
                     '%d mapped, %d scaffold stub(s)\n'
                     % (nfunc + ndata, nfunc, ndata,
                        nmapped, nfunc + ndata - nmapped))


if __name__ == '__main__':
    main()
