#!/usr/bin/env python3
#
# gen-export-roots.py -- emit a non-LTO anchor that roots every Xbox
# ordinal export.
#
# Under -flto the linker plugin owns symbol resolution and ld's PE
# .def-driven export handling no longer roots exported symbols: an
# export with no kernel-internal caller is dead-stripped outright, and
# the export address table is built from pre-LTRANS symbol values (see
# xb/fix-edata.py for that half of the problem).  This file takes the
# address of every export's backing symbol from a translation unit
# compiled -fno-lto, so the references are ordinary COFF relocations
# the plugin must satisfy.  The array lives in INITDATA and is
# discarded after Phase 1; pin it with -Wl,-u,_NxkExportRoots.
#
# usage: gen-export-roots.py <xboxkrnl.def> <out.c>
#
import re
import sys


def main():
    def_path, out_path = sys.argv[1], sys.argv[2]
    out = [
        '/* Generated by ntoskrnl/xb/gen-export-roots.py -- do not edit. */',
        '',
    ]
    refs = []
    in_exports = False
    for raw in open(def_path):
        line = raw.strip()
        if not line or line.startswith(';'):
            continue
        if line == 'EXPORTS':
            in_exports = True
            continue
        if not in_exports:
            continue
        head = line.split()[0]
        if '=' in head:
            name, sym = head.split('=', 1)
        else:
            name = sym = head
        if not name or '.' in sym:
            continue
        if sym.startswith('@'):              # fastcall: @Name@N
            target = sym
        else:                                # stdcall Name@N / cdecl / data
            target = '_' + sym
        n = len(refs)
        out.append('extern char S%d[] __asm__("%s");' % (n, target))
        refs.append('S%d' % n)

    out.append('')
    out.append('__attribute__((used, section("INITDATA")))')
    out.append('const void *const NxkExportRoots[%d]' % len(refs))
    out.append('    __asm__("_NxkExportRoots") = {')
    for r in refs:
        out.append('    %s,' % r)
    out.append('};')
    out.append('')
    with open(out_path, 'w') as f:
        f.write('\n'.join(out))
    sys.stderr.write('gen-export-roots: %d exports rooted\n' % len(refs))


if __name__ == '__main__':
    main()
