#!/usr/bin/env python3
#
# gen-version.py -- bake the kernel version banner into the image.
#
# Reads the project release version from the root VERSION file and, in a
# git checkout, appends a `git describe` build id.  The banner lives in
# INITDATA and NxkPrintVersionBanner() (INIT section) prints it on the
# debug serial at boot -- both are discarded after boot, so there is no
# resident-image cost.  The XboxKrnlVersion ordinal is a separate
# retail-compatibility constant and is unrelated to this string.
#
# usage: gen-version.py <repo-root> <VERSION-file> <out.c>

import subprocess
import sys


def git_build_id(root):
    """Short HEAD SHA plus a -dirty marker, or "" outside a git checkout.

    Deliberately not `git describe`: the tree carries ReactOS's own tags
    (0.4.x, v0.4.7), which describe would latch onto and misreport as our
    lineage.  The release version comes from the VERSION file; this is only
    the exact-build identifier."""
    try:
        sha = subprocess.check_output(
            ["git", "-C", root, "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL).decode("ascii", "replace").strip()
    except Exception:
        return ""
    try:
        dirty = subprocess.check_output(
            ["git", "-C", root, "status", "--porcelain"],
            stderr=subprocess.DEVNULL).decode("ascii", "replace").strip()
    except Exception:
        dirty = ""
    return sha + ("-dirty" if dirty else "")


def main(argv):
    if len(argv) != 4:
        sys.stderr.write("usage: gen-version.py <repo-root> <VERSION> <out.c>\n")
        return 1
    root, verfile, outpath = argv[1], argv[2], argv[3]
    try:
        with open(verfile) as f:
            version = f.read().strip()
    except OSError:
        version = "0.0.0"

    banner = "nxkrnl %s" % version
    build_id = git_build_id(root)
    if build_id:
        banner += " (%s)" % build_id
    banner = banner.replace("\\", "\\\\").replace('"', '\\"')

    with open(outpath, "w") as out:
        out.write("/* Generated by xb/gen-version.py -- do not edit. */\n")
        out.write("#include <ntoskrnl.h>\n")
        out.write("#include <debug.h>\n\n")
        out.write("/* Read by NxkPrintVersionBanner (debug serial, ex/init.c) and by the\n")
        out.write(" * boot-splash overlay (inbv/bootanim.c).  INITDATA: discarded after boot. */\n")
        out.write('DATA_SEG("INITDATA")\n')
        out.write('const CHAR NxkVersionBanner[] = "%s";\n\n' % banner)
        out.write('CODE_SEG("INIT")\n')
        out.write("VOID\n")
        out.write("NxkPrintVersionBanner(VOID)\n")
        out.write("{\n")
        out.write('    DbgPrint("%s\\n", NxkVersionBanner);\n')
        out.write("}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
