#!/usr/bin/env python3
#
# gen-nxkrnl-nls.py -- embed the Unicode case-mapping table into the kernel.
#
# Filesystem paths on Xbox flow through ANSI_STRING (byte buffers), so the
# kernel never converts title-supplied path bytes through codepage tables.
# The 66 KB CP-1252 (ANSI) and 66 KB CP-437 (OEM) tables are gone; the Rtl*
# codepage routines fall through to the ASCII fast-paths in
# ntoskrnl/xb/nls-stubs.c.
#
# The 4.8 KB Unicode case table (l_intl.nls) stays embedded -- it drives
# RtlpUpcaseUnicodeChar / RtlpDowncaseUnicodeChar for FATX / ISO-9660 case-
# insensitive lookup, object namespace, FsRtl wildcard, module-name compare.
#
# usage: gen-nxkrnl-nls.py <case.nls> <out.c>

import sys


def emit(out, name, data):
    out.write("const unsigned long %sSize = %d;\n" % (name, len(data)))
    out.write("const unsigned char %s[%d] =\n{\n" % (name, len(data)))
    for i in range(0, len(data), 16):
        out.write("    " + "".join("0x%02x," % b for b in data[i:i + 16]) + "\n")
    out.write("};\n\n")


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen-nxkrnl-nls.py <case> <out.c>\n")
        return 1

    case = open(sys.argv[1], "rb").read()

    with open(sys.argv[2], "w") as out:
        out.write("/* Generated by gen-nxkrnl-nls.py -- do not edit. */\n")
        out.write("/* Embedded Unicode case-mapping table. */\n\n")
        emit(out, "NxkrnlNlsCase", case)

    return 0


if __name__ == "__main__":
    sys.exit(main())
