if(SARCH STREQUAL "xbox")
    add_subdirectory(class)
    add_subdirectory(ide)
    add_subdirectory(mountmgr)
    add_subdirectory(partmgr)
    return()
endif()

add_subdirectory(class)
add_subdirectory(floppy)
add_subdirectory(ide)
add_subdirectory(mountmgr)
add_subdirectory(partmgr)
add_subdirectory(port)
