# contiguous-PA probe XBE -- finds the largest single
# MmAllocateContiguousMemoryEx the kernel can grant.  See main.c.
XBE_TITLE = nxkrnl-contig-probe
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS = $(CURDIR)/main.c
include $(NXDK_DIR)/Makefile
