XBE_TITLE = nxkrnl-api-regression
GEN_XISO = $(XBE_TITLE).iso
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS = $(CURDIR)/main.c $(CURDIR)/tap.c \
       $(CURDIR)/rtl/status.c \
       $(CURDIR)/rtl/string.c \
       $(CURDIR)/rtl/time.c \
       $(CURDIR)/rtl/zeromemory.c \
       $(CURDIR)/ke/event.c \
       $(CURDIR)/ke/semaphore.c \
       $(CURDIR)/ke/time.c \
       $(CURDIR)/ex/pool.c \
       $(CURDIR)/mm/contig.c \
       $(CURDIR)/io/file.c \
       $(CURDIR)/io/dvd.c \
       $(CURDIR)/hal/data.c \
       $(CURDIR)/ob/types.c \
       $(CURDIR)/ps/thread.c \
       $(CURDIR)/ke/wait_apc.c \
       $(CURDIR)/mm/virtual.c \
       $(CURDIR)/io/dirmask.c \
       $(CURDIR)/ob/named.c \
       $(CURDIR)/io/bad_ptr.c \
       $(CURDIR)/mm/bigpool.c \
       $(CURDIR)/io/cc_write.c \
       $(CURDIR)/io/storage.c \
       $(CURDIR)/io/complete.c \
       $(CURDIR)/xe/sections.c \
       $(CURDIR)/mm/vmcontract.c \
       $(CURDIR)/mm/cache.c \
       $(CURDIR)/io/mdl.c \
       $(CURDIR)/ke/waitmulti.c \
       $(CURDIR)/ob/symlink.c \
       $(CURDIR)/io/finfo.c \
       $(CURDIR)/io/rawfs.c \
       $(CURDIR)/ke/exceptions.c \
       $(CURDIR)/io/fatx16.c \
       $(CURDIR)/ob/handles.c \
       $(CURDIR)/hal/av.c \
       $(CURDIR)/mm/pressure.c
include $(NXDK_DIR)/Makefile
