# PHY-init test XBE -- exercises PhyInitialize and
# PhyGetLinkState.  See main.c.
XBE_TITLE = nxkrnl-phy-test
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS = $(CURDIR)/main.c
include $(NXDK_DIR)/Makefile
