XBE_TITLE = nxkrnl-hw-probe
GEN_XISO = $(XBE_TITLE).iso
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS = $(CURDIR)/main.c
NXDK_CFLAGS += -DENABLE_DEBUG_MSG -DENABLE_ERROR_MSG
include $(NXDK_DIR)/Makefile
