# Measure PhyInitialize / PhyGetLinkState wall time.  See main.c.
XBE_TITLE = phy-time
GEN_XISO  = $(XBE_TITLE).iso
NXDK_DIR ?= $(CURDIR)/../../../third_party/nxdk
SRCS      = $(CURDIR)/main.c
include $(NXDK_DIR)/Makefile
